### ISSUE TITLE
Issue when use it with flink

### ISSUE THREAD

**Issue by XiangChen666** [yyvess/Guice-configuration#14]
Caused by: java.io.NotSerializableException: net.jmob.guice.conf.core.internal.virtual.VirtualBean
I have declared InjectConfig in sink class.  The  problem is class above is not serializable. Is it possible I can make it serializable?

**Comment by yyvess** [comment]
Sorry for the delay ;-)
It's not possible as the class have one field Map of Object is not serializable.
